const DOMAIN = 'MOVIE';

export default {
    DISCOVER_MOVIE: `${DOMAIN}/DISCOVER_MOVIE`,
    DISCOVER_MOVIE_SUCCESS: `${DOMAIN}/DISCOVER_MOVIE_SUCCESS`,
    CLEAR_MOVIES: `${DOMAIN}/CLEAR_MOVIES`,
    GET_MOVIE_DETAIL: `${DOMAIN}/GET_MOVIE_DETAIL`,
};
